[[override]]
  name = "github.com/asecurityteam/settings"
  version = "^0.1.0"

[[constraint]]
  name = "github.com/asecurityteam/component-stat"
  version = "^0.1.0"

[[constraint]]
  name = "github.com/asecurityteam/component-log"
  version = "^0.1.0"

[[constraint]]
  name = "github.com/asecurityteam/component-connstate"
  version = "^0.1.0"

[[constraint]]
  name = "github.com/asecurityteam/component-expvar"
  version = "^0.1.0"

[[constraint]]
  name = "github.com/asecurityteam/component-signals"
  version = "^0.1.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
