[[constraint]]
  name = "github.com/asecurityteam/settings"
  branch = "master"

[[constraint]]
  name = "github.com/asecurityteam/logevent"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/rs/xstats"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
